# Generated by Django 6.0.4 on 2026-04-19 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('poste', models.CharField(max_length=50)),
                ('date_embauche', models.DateField()),
                ('statut', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('admin_rh', 'Administrateur RH'), ('employe', 'Employé')], default='employe', max_length=20)),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='personnel.departement')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_conge', models.CharField(choices=[('annuel', 'Congé annuel'), ('maladie', 'Congé maladie'), ('exceptionnel', 'Congé exceptionnel'), ('sans_solde', 'Congé sans solde')], max_length=50)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuve', 'Approuvé'), ('refuse', 'Refusé'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('justificatif_texte', models.TextField(blank=True, null=True)),
                ('justificatif_fichier', models.FileField(blank=True, null=True, upload_to='justificatifs/conges/')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='personnel.employe')),
            ],
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('conge', 'En congé')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='personnel.employe')),
            ],
            options={
                'unique_together': {('employe', 'date')},
            },
        ),
    ]
