# Generated by Django 6.0.4 on 2026-04-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_departement_alter_employe_departement'),
    ]

    operations = [
        migrations.AddField(
            model_name='conge',
            name='vu_par_employe',
            field=models.BooleanField(default=False, help_text="Indique si l'employé a vu la réponse (accepté/refusé) des RH"),
        ),
    ]
