# Generated by Django 6.0.4 on 2026-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_conge_vu_par_employe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametresApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='RHOPTIMA', max_length=100)),
                ('code_admin', models.CharField(default='adminrh2025', max_length=50)),
                ('jours_conge_annuel', models.IntegerField(default=30)),
            ],
        ),
    ]
